# name: Create Release Draft

# on:
#   workflow_dispatch:
#     inputs:
#       tag_name:
#         description: 'Tag name for the release'
#         required: true
#       branchName:
#           description: 'Branch Name'
#           required: true

# jobs:
#   create_release_draft:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.inputs.branchName }}

#       - name: Create source code archive (ZIP)
#         run: |
#           mkdir -p dist
#           zip -r dist/source-code.zip . -x "*.git*" -x "*.git/*"

#       - name: Create source code archive (TAR.GZ)
#         run: |
#           mkdir -p dist
#           tar --exclude='.git' -czf dist/source-code.tar.gz .

#       - name: Create Release Draft
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ github.event.inputs.tag_name }}
#           release_name: ${{ github.event.inputs.tag_name }}
#           draft: true
#           prerelease: false

#       - name: Upload Source Code Archive (ZIP)
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./dist/source-code.zip
#           asset_name: source-code.zip
#           asset_content_type: application/zip

#       - name: Upload Source Code Archive (TAR.GZ)
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./dist/source-code.tar.gz
#           asset_name: source-code.tar.gz
#           asset_content_type: application/gzip

name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
